name: MozeAfk
main: com.xbaimiao.minecraft.exppond.Main
version: 2.0.0
api-version: 1.18
author: Moze
description: 多区挂机池插件
commands:
  mozeafk:
    description: 挂机池管理命令
    usage: /<command> [wand|create|reload]
    aliases: [mzk]
    permission: op
    permission-message: &4小小沫说：你没有权限使用此命令
